# Environment & Data

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df_subdistricts = pd.read_csv('../data/master_tables/berlin_ortsteil_master_with_poi_features.csv')

# Data Overview

In [3]:
df_subdistricts.shape

(96, 66)

In [5]:
df_subdistricts.head(12)

,bezirk,ortsteil,subdistrict_population_age_0_5,subdistrict_population_age_5_10,subdistrict_population_age_10_15,subdistrict_population_age_15_20,subdistrict_population_age_20_25,subdistrict_population_age_25_30,subdistrict_population_age_30_35,subdistrict_population_age_35_40,...,parking,subdistrict_num_pharmacies,pitch,subdistrict_num_playgrounds,subdistrict_num_restaurants,subdistrict_num_schools,subdistrict_num_supermarkets,theatre,subdistrict_num_universities,subdistrict_num_wood_areas
0,treptow-koepenick,adlershof,1177.0,846.0,710.0,671.0,1410.0,1765.0,2274.0,1833.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,lichtenberg,alt-hohenschoenhausen,2960.0,2689.0,2308.0,1975.0,2360.0,2943.0,4609.0,3963.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,treptow-koepenick,alt-treptow,840.0,727.0,560.0,450.0,457.0,895.0,1617.0,1685.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,treptow-koepenick,altglienicke,1724.0,1788.0,1631.0,1391.0,1417.0,1411.0,2162.0,2134.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,treptow-koepenick,baumschulenweg,880.0,732.0,620.0,569.0,866.0,1374.0,2107.0,1669.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5,marzahn-hellersdorf,biesdorf,1332.0,1356.0,1170.0,1042.0,1258.0,1254.0,1700.0,1966.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6,pankow,blankenburg,274.0,388.0,358.0,302.0,226.0,138.0,276.0,460.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7,pankow,blankenfelde,69.0,108.0,106.0,77.0,52.0,46.0,100.0,107.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
8,treptow-koepenick,bohnsdorf,537.0,532.0,530.0,471.0,461.0,397.0,664.0,751.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
9,reinickendorf,borsigwalde,310.0,240.0,222.0,207.0,405.0,552.0,600.0,429.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
10,neukoelln,britz,2095.0,2041.0,1811.0,1695.0,2407.0,3211.0,3456.0,3030.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
11,pankow,buch,1050.0,895.0,774.0,647.0,761.0,852.0,1355.0,1347.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0